/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWarehouseRouteImport } from './routes/_authenticated/warehouse'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedLogisticsRouteImport } from './routes/_authenticated/logistics'
import { Route as AuthenticatedLayoutsRouteImport } from './routes/_authenticated/layouts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedReservationsIndexRouteImport } from './routes/_authenticated/reservations.index'
import { Route as AuthenticatedSettingsCalendarRouteImport } from './routes/_authenticated/settings.calendar'
import { Route as AuthenticatedReservationsNewRouteImport } from './routes/_authenticated/reservations.new'
import { Route as AuthenticatedReservationsIdRouteImport } from './routes/_authenticated/reservations.$id'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'
import { Route as AuthenticatedReservationsIdIndexRouteImport } from './routes/_authenticated/reservations.$id.index'
import { Route as ApiPublicCalendarTokenRouteImport } from './routes/api/public/calendar.$token'
import { Route as AuthenticatedReservationsIdLayoutRouteImport } from './routes/_authenticated/reservations.$id.layout'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWarehouseRoute = AuthenticatedWarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogisticsRoute = AuthenticatedLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLayoutsRoute = AuthenticatedLayoutsRouteImport.update({
  id: '/layouts',
  path: '/layouts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedReservationsIndexRoute =
  AuthenticatedReservationsIndexRouteImport.update({
    id: '/reservations/',
    path: '/reservations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsCalendarRoute =
  AuthenticatedSettingsCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedReservationsNewRoute =
  AuthenticatedReservationsNewRouteImport.update({
    id: '/reservations/new',
    path: '/reservations/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReservationsIdRoute =
  AuthenticatedReservationsIdRouteImport.update({
    id: '/reservations/$id',
    path: '/reservations/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientsRoute,
} as any)
const AuthenticatedReservationsIdIndexRoute =
  AuthenticatedReservationsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReservationsIdRoute,
  } as any)
const ApiPublicCalendarTokenRoute = ApiPublicCalendarTokenRouteImport.update({
  id: '/api/public/calendar/$token',
  path: '/api/public/calendar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReservationsIdLayoutRoute =
  AuthenticatedReservationsIdLayoutRouteImport.update({
    id: '/layout',
    path: '/layout',
    getParentRoute: () => AuthenticatedReservationsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/layouts': typeof AuthenticatedLayoutsRoute
  '/logistics': typeof AuthenticatedLogisticsRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/warehouse': typeof AuthenticatedWarehouseRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/reservations/$id': typeof AuthenticatedReservationsIdRouteWithChildren
  '/reservations/new': typeof AuthenticatedReservationsNewRoute
  '/settings/calendar': typeof AuthenticatedSettingsCalendarRoute
  '/reservations/': typeof AuthenticatedReservationsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/reservations/$id/layout': typeof AuthenticatedReservationsIdLayoutRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/reservations/$id/': typeof AuthenticatedReservationsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/layouts': typeof AuthenticatedLayoutsRoute
  '/logistics': typeof AuthenticatedLogisticsRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/users': typeof AuthenticatedUsersRoute
  '/warehouse': typeof AuthenticatedWarehouseRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/reservations/new': typeof AuthenticatedReservationsNewRoute
  '/settings/calendar': typeof AuthenticatedSettingsCalendarRoute
  '/reservations': typeof AuthenticatedReservationsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/reservations/$id/layout': typeof AuthenticatedReservationsIdLayoutRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/reservations/$id': typeof AuthenticatedReservationsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/layouts': typeof AuthenticatedLayoutsRoute
  '/_authenticated/logistics': typeof AuthenticatedLogisticsRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/warehouse': typeof AuthenticatedWarehouseRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/reservations/$id': typeof AuthenticatedReservationsIdRouteWithChildren
  '/_authenticated/reservations/new': typeof AuthenticatedReservationsNewRoute
  '/_authenticated/settings/calendar': typeof AuthenticatedSettingsCalendarRoute
  '/_authenticated/reservations/': typeof AuthenticatedReservationsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/reservations/$id/layout': typeof AuthenticatedReservationsIdLayoutRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/_authenticated/reservations/$id/': typeof AuthenticatedReservationsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clients'
    | '/dashboard'
    | '/layouts'
    | '/logistics'
    | '/maintenance'
    | '/settings'
    | '/users'
    | '/warehouse'
    | '/clients/$id'
    | '/reservations/$id'
    | '/reservations/new'
    | '/settings/calendar'
    | '/reservations/'
    | '/settings/'
    | '/reservations/$id/layout'
    | '/api/public/calendar/$token'
    | '/reservations/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clients'
    | '/dashboard'
    | '/layouts'
    | '/logistics'
    | '/maintenance'
    | '/users'
    | '/warehouse'
    | '/clients/$id'
    | '/reservations/new'
    | '/settings/calendar'
    | '/reservations'
    | '/settings'
    | '/reservations/$id/layout'
    | '/api/public/calendar/$token'
    | '/reservations/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/layouts'
    | '/_authenticated/logistics'
    | '/_authenticated/maintenance'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/warehouse'
    | '/_authenticated/clients/$id'
    | '/_authenticated/reservations/$id'
    | '/_authenticated/reservations/new'
    | '/_authenticated/settings/calendar'
    | '/_authenticated/reservations/'
    | '/_authenticated/settings/'
    | '/_authenticated/reservations/$id/layout'
    | '/api/public/calendar/$token'
    | '/_authenticated/reservations/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCalendarTokenRoute: typeof ApiPublicCalendarTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/warehouse': {
      id: '/_authenticated/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof AuthenticatedWarehouseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logistics': {
      id: '/_authenticated/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof AuthenticatedLogisticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/layouts': {
      id: '/_authenticated/layouts'
      path: '/layouts'
      fullPath: '/layouts'
      preLoaderRoute: typeof AuthenticatedLayoutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/reservations/': {
      id: '/_authenticated/reservations/'
      path: '/reservations'
      fullPath: '/reservations/'
      preLoaderRoute: typeof AuthenticatedReservationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/calendar': {
      id: '/_authenticated/settings/calendar'
      path: '/calendar'
      fullPath: '/settings/calendar'
      preLoaderRoute: typeof AuthenticatedSettingsCalendarRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/reservations/new': {
      id: '/_authenticated/reservations/new'
      path: '/reservations/new'
      fullPath: '/reservations/new'
      preLoaderRoute: typeof AuthenticatedReservationsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservations/$id': {
      id: '/_authenticated/reservations/$id'
      path: '/reservations/$id'
      fullPath: '/reservations/$id'
      preLoaderRoute: typeof AuthenticatedReservationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/reservations/$id/': {
      id: '/_authenticated/reservations/$id/'
      path: '/'
      fullPath: '/reservations/$id/'
      preLoaderRoute: typeof AuthenticatedReservationsIdIndexRouteImport
      parentRoute: typeof AuthenticatedReservationsIdRoute
    }
    '/api/public/calendar/$token': {
      id: '/api/public/calendar/$token'
      path: '/api/public/calendar/$token'
      fullPath: '/api/public/calendar/$token'
      preLoaderRoute: typeof ApiPublicCalendarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reservations/$id/layout': {
      id: '/_authenticated/reservations/$id/layout'
      path: '/layout'
      fullPath: '/reservations/$id/layout'
      preLoaderRoute: typeof AuthenticatedReservationsIdLayoutRouteImport
      parentRoute: typeof AuthenticatedReservationsIdRoute
    }
  }
}

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsCalendarRoute: typeof AuthenticatedSettingsCalendarRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsCalendarRoute: AuthenticatedSettingsCalendarRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedReservationsIdRouteChildren {
  AuthenticatedReservationsIdLayoutRoute: typeof AuthenticatedReservationsIdLayoutRoute
  AuthenticatedReservationsIdIndexRoute: typeof AuthenticatedReservationsIdIndexRoute
}

const AuthenticatedReservationsIdRouteChildren: AuthenticatedReservationsIdRouteChildren =
  {
    AuthenticatedReservationsIdLayoutRoute:
      AuthenticatedReservationsIdLayoutRoute,
    AuthenticatedReservationsIdIndexRoute:
      AuthenticatedReservationsIdIndexRoute,
  }

const AuthenticatedReservationsIdRouteWithChildren =
  AuthenticatedReservationsIdRoute._addFileChildren(
    AuthenticatedReservationsIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLayoutsRoute: typeof AuthenticatedLayoutsRoute
  AuthenticatedLogisticsRoute: typeof AuthenticatedLogisticsRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWarehouseRoute: typeof AuthenticatedWarehouseRoute
  AuthenticatedReservationsIdRoute: typeof AuthenticatedReservationsIdRouteWithChildren
  AuthenticatedReservationsNewRoute: typeof AuthenticatedReservationsNewRoute
  AuthenticatedReservationsIndexRoute: typeof AuthenticatedReservationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLayoutsRoute: AuthenticatedLayoutsRoute,
  AuthenticatedLogisticsRoute: AuthenticatedLogisticsRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWarehouseRoute: AuthenticatedWarehouseRoute,
  AuthenticatedReservationsIdRoute:
    AuthenticatedReservationsIdRouteWithChildren,
  AuthenticatedReservationsNewRoute: AuthenticatedReservationsNewRoute,
  AuthenticatedReservationsIndexRoute: AuthenticatedReservationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCalendarTokenRoute: ApiPublicCalendarTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
