/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DotaznikTokenRouteImport } from './routes/dotaznik.$token'
import { Route as AuthenticatedWarehouseRouteImport } from './routes/_authenticated/warehouse'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSurveysRouteImport } from './routes/_authenticated/surveys'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedLogisticsRouteImport } from './routes/_authenticated/logistics'
import { Route as AuthenticatedLayoutsRouteImport } from './routes/_authenticated/layouts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedReservationsIndexRouteImport } from './routes/_authenticated/reservations.index'
import { Route as AuthenticatedQuotesIndexRouteImport } from './routes/_authenticated/quotes.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedWarehouseQrPrintRouteImport } from './routes/_authenticated/warehouse.qr-print'
import { Route as AuthenticatedSettingsCalendarRouteImport } from './routes/_authenticated/settings.calendar'
import { Route as AuthenticatedReservationsNewRouteImport } from './routes/_authenticated/reservations.new'
import { Route as AuthenticatedReservationsIdRouteImport } from './routes/_authenticated/reservations.$id'
import { Route as AuthenticatedQuotesNewRouteImport } from './routes/_authenticated/quotes.new'
import { Route as AuthenticatedQuotesIdRouteImport } from './routes/_authenticated/quotes.$id'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'
import { Route as AuthenticatedReservationsIdIndexRouteImport } from './routes/_authenticated/reservations.$id.index'
import { Route as ApiPublicHooksWarehouseBackupRouteImport } from './routes/api/public/hooks/warehouse-backup'
import { Route as ApiPublicCalendarTokenRouteImport } from './routes/api/public/calendar.$token'
import { Route as AuthenticatedWarehouseScanIdRouteImport } from './routes/_authenticated/warehouse.scan.$id'
import { Route as AuthenticatedReservationsIdLayoutRouteImport } from './routes/_authenticated/reservations.$id.layout'
import { Route as AuthenticatedDocumentsProtocolIdRouteImport } from './routes/_authenticated/documents.protocol.$id'
import { Route as AuthenticatedDocumentsContractIdRouteImport } from './routes/_authenticated/documents.contract.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DotaznikTokenRoute = DotaznikTokenRouteImport.update({
  id: '/dotaznik/$token',
  path: '/dotaznik/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWarehouseRoute = AuthenticatedWarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSurveysRoute = AuthenticatedSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogisticsRoute = AuthenticatedLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLayoutsRoute = AuthenticatedLayoutsRouteImport.update({
  id: '/layouts',
  path: '/layouts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedReservationsIndexRoute =
  AuthenticatedReservationsIndexRouteImport.update({
    id: '/reservations/',
    path: '/reservations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotesIndexRoute =
  AuthenticatedQuotesIndexRouteImport.update({
    id: '/quotes/',
    path: '/quotes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWarehouseQrPrintRoute =
  AuthenticatedWarehouseQrPrintRouteImport.update({
    id: '/qr-print',
    path: '/qr-print',
    getParentRoute: () => AuthenticatedWarehouseRoute,
  } as any)
const AuthenticatedSettingsCalendarRoute =
  AuthenticatedSettingsCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedReservationsNewRoute =
  AuthenticatedReservationsNewRouteImport.update({
    id: '/reservations/new',
    path: '/reservations/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReservationsIdRoute =
  AuthenticatedReservationsIdRouteImport.update({
    id: '/reservations/$id',
    path: '/reservations/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotesNewRoute = AuthenticatedQuotesNewRouteImport.update({
  id: '/quotes/new',
  path: '/quotes/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotesIdRoute = AuthenticatedQuotesIdRouteImport.update({
  id: '/quotes/$id',
  path: '/quotes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReservationsIdIndexRoute =
  AuthenticatedReservationsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReservationsIdRoute,
  } as any)
const ApiPublicHooksWarehouseBackupRoute =
  ApiPublicHooksWarehouseBackupRouteImport.update({
    id: '/api/public/hooks/warehouse-backup',
    path: '/api/public/hooks/warehouse-backup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCalendarTokenRoute = ApiPublicCalendarTokenRouteImport.update({
  id: '/api/public/calendar/$token',
  path: '/api/public/calendar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWarehouseScanIdRoute =
  AuthenticatedWarehouseScanIdRouteImport.update({
    id: '/scan/$id',
    path: '/scan/$id',
    getParentRoute: () => AuthenticatedWarehouseRoute,
  } as any)
const AuthenticatedReservationsIdLayoutRoute =
  AuthenticatedReservationsIdLayoutRouteImport.update({
    id: '/layout',
    path: '/layout',
    getParentRoute: () => AuthenticatedReservationsIdRoute,
  } as any)
const AuthenticatedDocumentsProtocolIdRoute =
  AuthenticatedDocumentsProtocolIdRouteImport.update({
    id: '/documents/protocol/$id',
    path: '/documents/protocol/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsContractIdRoute =
  AuthenticatedDocumentsContractIdRouteImport.update({
    id: '/documents/contract/$id',
    path: '/documents/contract/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/layouts': typeof AuthenticatedLayoutsRoute
  '/logistics': typeof AuthenticatedLogisticsRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/surveys': typeof AuthenticatedSurveysRoute
  '/users': typeof AuthenticatedUsersRoute
  '/warehouse': typeof AuthenticatedWarehouseRouteWithChildren
  '/dotaznik/$token': typeof DotaznikTokenRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/quotes/$id': typeof AuthenticatedQuotesIdRoute
  '/quotes/new': typeof AuthenticatedQuotesNewRoute
  '/reservations/$id': typeof AuthenticatedReservationsIdRouteWithChildren
  '/reservations/new': typeof AuthenticatedReservationsNewRoute
  '/settings/calendar': typeof AuthenticatedSettingsCalendarRoute
  '/warehouse/qr-print': typeof AuthenticatedWarehouseQrPrintRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/quotes/': typeof AuthenticatedQuotesIndexRoute
  '/reservations/': typeof AuthenticatedReservationsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/documents/contract/$id': typeof AuthenticatedDocumentsContractIdRoute
  '/documents/protocol/$id': typeof AuthenticatedDocumentsProtocolIdRoute
  '/reservations/$id/layout': typeof AuthenticatedReservationsIdLayoutRoute
  '/warehouse/scan/$id': typeof AuthenticatedWarehouseScanIdRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/hooks/warehouse-backup': typeof ApiPublicHooksWarehouseBackupRoute
  '/reservations/$id/': typeof AuthenticatedReservationsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/layouts': typeof AuthenticatedLayoutsRoute
  '/logistics': typeof AuthenticatedLogisticsRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/surveys': typeof AuthenticatedSurveysRoute
  '/users': typeof AuthenticatedUsersRoute
  '/warehouse': typeof AuthenticatedWarehouseRouteWithChildren
  '/dotaznik/$token': typeof DotaznikTokenRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/quotes/$id': typeof AuthenticatedQuotesIdRoute
  '/quotes/new': typeof AuthenticatedQuotesNewRoute
  '/reservations/new': typeof AuthenticatedReservationsNewRoute
  '/settings/calendar': typeof AuthenticatedSettingsCalendarRoute
  '/warehouse/qr-print': typeof AuthenticatedWarehouseQrPrintRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/quotes': typeof AuthenticatedQuotesIndexRoute
  '/reservations': typeof AuthenticatedReservationsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/documents/contract/$id': typeof AuthenticatedDocumentsContractIdRoute
  '/documents/protocol/$id': typeof AuthenticatedDocumentsProtocolIdRoute
  '/reservations/$id/layout': typeof AuthenticatedReservationsIdLayoutRoute
  '/warehouse/scan/$id': typeof AuthenticatedWarehouseScanIdRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/hooks/warehouse-backup': typeof ApiPublicHooksWarehouseBackupRoute
  '/reservations/$id': typeof AuthenticatedReservationsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/layouts': typeof AuthenticatedLayoutsRoute
  '/_authenticated/logistics': typeof AuthenticatedLogisticsRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/surveys': typeof AuthenticatedSurveysRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/warehouse': typeof AuthenticatedWarehouseRouteWithChildren
  '/dotaznik/$token': typeof DotaznikTokenRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/quotes/$id': typeof AuthenticatedQuotesIdRoute
  '/_authenticated/quotes/new': typeof AuthenticatedQuotesNewRoute
  '/_authenticated/reservations/$id': typeof AuthenticatedReservationsIdRouteWithChildren
  '/_authenticated/reservations/new': typeof AuthenticatedReservationsNewRoute
  '/_authenticated/settings/calendar': typeof AuthenticatedSettingsCalendarRoute
  '/_authenticated/warehouse/qr-print': typeof AuthenticatedWarehouseQrPrintRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/quotes/': typeof AuthenticatedQuotesIndexRoute
  '/_authenticated/reservations/': typeof AuthenticatedReservationsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/documents/contract/$id': typeof AuthenticatedDocumentsContractIdRoute
  '/_authenticated/documents/protocol/$id': typeof AuthenticatedDocumentsProtocolIdRoute
  '/_authenticated/reservations/$id/layout': typeof AuthenticatedReservationsIdLayoutRoute
  '/_authenticated/warehouse/scan/$id': typeof AuthenticatedWarehouseScanIdRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/hooks/warehouse-backup': typeof ApiPublicHooksWarehouseBackupRoute
  '/_authenticated/reservations/$id/': typeof AuthenticatedReservationsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/layouts'
    | '/logistics'
    | '/maintenance'
    | '/settings'
    | '/surveys'
    | '/users'
    | '/warehouse'
    | '/dotaznik/$token'
    | '/clients/$id'
    | '/quotes/$id'
    | '/quotes/new'
    | '/reservations/$id'
    | '/reservations/new'
    | '/settings/calendar'
    | '/warehouse/qr-print'
    | '/clients/'
    | '/quotes/'
    | '/reservations/'
    | '/settings/'
    | '/documents/contract/$id'
    | '/documents/protocol/$id'
    | '/reservations/$id/layout'
    | '/warehouse/scan/$id'
    | '/api/public/calendar/$token'
    | '/api/public/hooks/warehouse-backup'
    | '/reservations/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/layouts'
    | '/logistics'
    | '/maintenance'
    | '/surveys'
    | '/users'
    | '/warehouse'
    | '/dotaznik/$token'
    | '/clients/$id'
    | '/quotes/$id'
    | '/quotes/new'
    | '/reservations/new'
    | '/settings/calendar'
    | '/warehouse/qr-print'
    | '/clients'
    | '/quotes'
    | '/reservations'
    | '/settings'
    | '/documents/contract/$id'
    | '/documents/protocol/$id'
    | '/reservations/$id/layout'
    | '/warehouse/scan/$id'
    | '/api/public/calendar/$token'
    | '/api/public/hooks/warehouse-backup'
    | '/reservations/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/layouts'
    | '/_authenticated/logistics'
    | '/_authenticated/maintenance'
    | '/_authenticated/settings'
    | '/_authenticated/surveys'
    | '/_authenticated/users'
    | '/_authenticated/warehouse'
    | '/dotaznik/$token'
    | '/_authenticated/clients/$id'
    | '/_authenticated/quotes/$id'
    | '/_authenticated/quotes/new'
    | '/_authenticated/reservations/$id'
    | '/_authenticated/reservations/new'
    | '/_authenticated/settings/calendar'
    | '/_authenticated/warehouse/qr-print'
    | '/_authenticated/clients/'
    | '/_authenticated/quotes/'
    | '/_authenticated/reservations/'
    | '/_authenticated/settings/'
    | '/_authenticated/documents/contract/$id'
    | '/_authenticated/documents/protocol/$id'
    | '/_authenticated/reservations/$id/layout'
    | '/_authenticated/warehouse/scan/$id'
    | '/api/public/calendar/$token'
    | '/api/public/hooks/warehouse-backup'
    | '/_authenticated/reservations/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DotaznikTokenRoute: typeof DotaznikTokenRoute
  ApiPublicCalendarTokenRoute: typeof ApiPublicCalendarTokenRoute
  ApiPublicHooksWarehouseBackupRoute: typeof ApiPublicHooksWarehouseBackupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dotaznik/$token': {
      id: '/dotaznik/$token'
      path: '/dotaznik/$token'
      fullPath: '/dotaznik/$token'
      preLoaderRoute: typeof DotaznikTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/warehouse': {
      id: '/_authenticated/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof AuthenticatedWarehouseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/surveys': {
      id: '/_authenticated/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof AuthenticatedSurveysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logistics': {
      id: '/_authenticated/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof AuthenticatedLogisticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/layouts': {
      id: '/_authenticated/layouts'
      path: '/layouts'
      fullPath: '/layouts'
      preLoaderRoute: typeof AuthenticatedLayoutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/reservations/': {
      id: '/_authenticated/reservations/'
      path: '/reservations'
      fullPath: '/reservations/'
      preLoaderRoute: typeof AuthenticatedReservationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes/': {
      id: '/_authenticated/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AuthenticatedQuotesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/warehouse/qr-print': {
      id: '/_authenticated/warehouse/qr-print'
      path: '/qr-print'
      fullPath: '/warehouse/qr-print'
      preLoaderRoute: typeof AuthenticatedWarehouseQrPrintRouteImport
      parentRoute: typeof AuthenticatedWarehouseRoute
    }
    '/_authenticated/settings/calendar': {
      id: '/_authenticated/settings/calendar'
      path: '/calendar'
      fullPath: '/settings/calendar'
      preLoaderRoute: typeof AuthenticatedSettingsCalendarRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/reservations/new': {
      id: '/_authenticated/reservations/new'
      path: '/reservations/new'
      fullPath: '/reservations/new'
      preLoaderRoute: typeof AuthenticatedReservationsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservations/$id': {
      id: '/_authenticated/reservations/$id'
      path: '/reservations/$id'
      fullPath: '/reservations/$id'
      preLoaderRoute: typeof AuthenticatedReservationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes/new': {
      id: '/_authenticated/quotes/new'
      path: '/quotes/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof AuthenticatedQuotesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes/$id': {
      id: '/_authenticated/quotes/$id'
      path: '/quotes/$id'
      fullPath: '/quotes/$id'
      preLoaderRoute: typeof AuthenticatedQuotesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservations/$id/': {
      id: '/_authenticated/reservations/$id/'
      path: '/'
      fullPath: '/reservations/$id/'
      preLoaderRoute: typeof AuthenticatedReservationsIdIndexRouteImport
      parentRoute: typeof AuthenticatedReservationsIdRoute
    }
    '/api/public/hooks/warehouse-backup': {
      id: '/api/public/hooks/warehouse-backup'
      path: '/api/public/hooks/warehouse-backup'
      fullPath: '/api/public/hooks/warehouse-backup'
      preLoaderRoute: typeof ApiPublicHooksWarehouseBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar/$token': {
      id: '/api/public/calendar/$token'
      path: '/api/public/calendar/$token'
      fullPath: '/api/public/calendar/$token'
      preLoaderRoute: typeof ApiPublicCalendarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/warehouse/scan/$id': {
      id: '/_authenticated/warehouse/scan/$id'
      path: '/scan/$id'
      fullPath: '/warehouse/scan/$id'
      preLoaderRoute: typeof AuthenticatedWarehouseScanIdRouteImport
      parentRoute: typeof AuthenticatedWarehouseRoute
    }
    '/_authenticated/reservations/$id/layout': {
      id: '/_authenticated/reservations/$id/layout'
      path: '/layout'
      fullPath: '/reservations/$id/layout'
      preLoaderRoute: typeof AuthenticatedReservationsIdLayoutRouteImport
      parentRoute: typeof AuthenticatedReservationsIdRoute
    }
    '/_authenticated/documents/protocol/$id': {
      id: '/_authenticated/documents/protocol/$id'
      path: '/documents/protocol/$id'
      fullPath: '/documents/protocol/$id'
      preLoaderRoute: typeof AuthenticatedDocumentsProtocolIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/contract/$id': {
      id: '/_authenticated/documents/contract/$id'
      path: '/documents/contract/$id'
      fullPath: '/documents/contract/$id'
      preLoaderRoute: typeof AuthenticatedDocumentsContractIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsCalendarRoute: typeof AuthenticatedSettingsCalendarRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsCalendarRoute: AuthenticatedSettingsCalendarRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedWarehouseRouteChildren {
  AuthenticatedWarehouseQrPrintRoute: typeof AuthenticatedWarehouseQrPrintRoute
  AuthenticatedWarehouseScanIdRoute: typeof AuthenticatedWarehouseScanIdRoute
}

const AuthenticatedWarehouseRouteChildren: AuthenticatedWarehouseRouteChildren =
  {
    AuthenticatedWarehouseQrPrintRoute: AuthenticatedWarehouseQrPrintRoute,
    AuthenticatedWarehouseScanIdRoute: AuthenticatedWarehouseScanIdRoute,
  }

const AuthenticatedWarehouseRouteWithChildren =
  AuthenticatedWarehouseRoute._addFileChildren(
    AuthenticatedWarehouseRouteChildren,
  )

interface AuthenticatedReservationsIdRouteChildren {
  AuthenticatedReservationsIdLayoutRoute: typeof AuthenticatedReservationsIdLayoutRoute
  AuthenticatedReservationsIdIndexRoute: typeof AuthenticatedReservationsIdIndexRoute
}

const AuthenticatedReservationsIdRouteChildren: AuthenticatedReservationsIdRouteChildren =
  {
    AuthenticatedReservationsIdLayoutRoute:
      AuthenticatedReservationsIdLayoutRoute,
    AuthenticatedReservationsIdIndexRoute:
      AuthenticatedReservationsIdIndexRoute,
  }

const AuthenticatedReservationsIdRouteWithChildren =
  AuthenticatedReservationsIdRoute._addFileChildren(
    AuthenticatedReservationsIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLayoutsRoute: typeof AuthenticatedLayoutsRoute
  AuthenticatedLogisticsRoute: typeof AuthenticatedLogisticsRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedSurveysRoute: typeof AuthenticatedSurveysRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWarehouseRoute: typeof AuthenticatedWarehouseRouteWithChildren
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
  AuthenticatedQuotesIdRoute: typeof AuthenticatedQuotesIdRoute
  AuthenticatedQuotesNewRoute: typeof AuthenticatedQuotesNewRoute
  AuthenticatedReservationsIdRoute: typeof AuthenticatedReservationsIdRouteWithChildren
  AuthenticatedReservationsNewRoute: typeof AuthenticatedReservationsNewRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedQuotesIndexRoute: typeof AuthenticatedQuotesIndexRoute
  AuthenticatedReservationsIndexRoute: typeof AuthenticatedReservationsIndexRoute
  AuthenticatedDocumentsContractIdRoute: typeof AuthenticatedDocumentsContractIdRoute
  AuthenticatedDocumentsProtocolIdRoute: typeof AuthenticatedDocumentsProtocolIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLayoutsRoute: AuthenticatedLayoutsRoute,
  AuthenticatedLogisticsRoute: AuthenticatedLogisticsRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedSurveysRoute: AuthenticatedSurveysRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWarehouseRoute: AuthenticatedWarehouseRouteWithChildren,
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
  AuthenticatedQuotesIdRoute: AuthenticatedQuotesIdRoute,
  AuthenticatedQuotesNewRoute: AuthenticatedQuotesNewRoute,
  AuthenticatedReservationsIdRoute:
    AuthenticatedReservationsIdRouteWithChildren,
  AuthenticatedReservationsNewRoute: AuthenticatedReservationsNewRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedQuotesIndexRoute: AuthenticatedQuotesIndexRoute,
  AuthenticatedReservationsIndexRoute: AuthenticatedReservationsIndexRoute,
  AuthenticatedDocumentsContractIdRoute: AuthenticatedDocumentsContractIdRoute,
  AuthenticatedDocumentsProtocolIdRoute: AuthenticatedDocumentsProtocolIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DotaznikTokenRoute: DotaznikTokenRoute,
  ApiPublicCalendarTokenRoute: ApiPublicCalendarTokenRoute,
  ApiPublicHooksWarehouseBackupRoute: ApiPublicHooksWarehouseBackupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
