// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olazrqpgirkbneghoikj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sYXpycXBnaXJrYm5lZ2hvaWtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIzNzUwMDgsImV4cCI6MjA5Nzk1MTAwOH0.XG6doV1rb2xS6Rrxe0T01cL0BQfgFXm-q4bI1nGdIug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});